
limits-service:
  minimum: 23
  maximum: 109
spring:
  application:
    name: limits-service
  profiles:
    active: qa
management:
  endpoints:
    web:
      exposure:
        include: refresh
LimitConfiguration:
  minimum: 0
  maximum: 1
